name: MoveTK-create-docker-image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-docker:
    # Temporarily disable
    if: false
    runs-on: ubuntu-latest

    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with:
            submodules: recursive
        - name: Get version
          run: echo "${{ github.ref }}"
        - name: Docker build
          run:  docker build -t movetk -f  ./docker/with_jupyterlab/Dockerfile .
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
              username: ${{ secrets.DOCKERHUB_USER }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}
              registry: "docker.io"
        - name: Docker push
          run:  docker tag movetk:latest aniketmitra001/movetk:latest && docker push aniketmitra001/movetk:latest
